[tools]
python = "3.13"

[env]
_.python.venv = ".venv"

[tasks.pull]
run = "uv run scripts/pull_db.py"

[tasks.push]
run = "uv run scripts/push_db.py"

[tasks.sync]
run = "uv run calsync process"

[tasks.cmd]
run = "uv run calsync"

[tasks.trigger]
run = "gh workflow run sync.yml"

[tasks."validate:ty"]
run = "uv run ty check"

[tasks."validate:ruff"]
run = "uv run ruff format"

[tasks.validate]
depends = ["validate:*"]
